# Generated by Django 4.2.8 on 2024-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consumption_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=7),
        ),
    ]
