# Generated by Django 4.2.8 on 2024-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_pharmacy_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='recent_prescriptions',
            field=models.ManyToManyField(blank=True, related_name='recent_prescriptions', to='hospitalapp.appointment'),
        ),
    ]
