# Generated by Django 4.2.8 on 2024-01-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_pharmacy_recent_prescriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='recent_prescriptions',
        ),
    ]
