# Generated by Django 4.2.8 on 2024-01-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.appointment'),
        ),
    ]
