# Generated by Django 4.2.8 on 2024-01-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
