# Generated by Django 4.2.8 on 2024-01-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_remove_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
