from django.urls import path,include
from .import views
from .views import change_password
urlpatterns = [
    path('',views.index,name='index'),
    path('nav',views.nav,name='nav'),
    path('nav2',views.nav2,name='nav2'),
    path('nav21',views.nav21,name='nav21'),
    path('nav3',views.nav3,name='nav3'),
    path('nav4',views.nav4,name='nav4'),
    path('reception',views.reception,name='reception'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('login_all',views.login_all,name='login_all'),
    path('add_department',views.add_department,name='add_department'),
    path('department',views.department,name='department'),
    path('register_patient', views.register_patient, name='register_patient'),
    path('appointment_form',views.appointment_form,name='appointment_form'),
    path('doctor_signup',views.doctor_signup,name='doctor_signup'),
    path('register_doctor',views.register_doctor,name='register_doctor'),
    path('doctor_home',views.doctor_home,name='doctor_home'),
    path('doctor_home1',views.doctor_home1,name='doctor_home1'),
    path('get_doctors_by_department/', views.get_doctors_by_department, name='get_doctors_by_department'),
    path('appointment_form/<str:patient_id>/',views.appointment_form, name='appointment_form'),
    path('appointment_details/<int:appointment_id>/',views.appointment_details, name='appointment_details'),
    path('search/',views.search_patient, name='search_patient'),
    path('patient_details/<str:patient_id>/',views.patient_details, name='patient_details'),
    path('appointment_list/',views.appointment_list, name='appointment_list'),
    path('consultation/<int:appointment_id>/',views.consultation, name='consultation'),
    path('reassign_patient/<int:appointment_id>/',views.reassign_patient, name='reassign_patient'),
    path('change_password/',views.change_password, name='change_password'),
    path('change_password_pharmacy/',views.change_password_pharmacy, name='change_password_pharmacy'),
    path('pharmacy_home',views.pharmacy_home,name='pharmacy_home'),
    path('pharmacy_home1',views.pharmacy_home1,name='pharmacy_home1'),
    path('signup_pharmacy/',views.signup_pharmacy, name='signup_pharmacy'),
    path('consulted-patient-details/',views.consulted_patient_details, name='consulted_patient_details'),
    path('doctor_consulted_patients/', views.doctor_consulted_patients, name='doctor_consulted_patients'),
    path('all_consulted_patients/', views.all_consulted_patients, name='all_consulted_patients'),
    path('all_departments/', views.all_departments, name='all_departments'),
    path('edit_department/<int:department_id>/', views.edit_department, name='edit_department'),
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('logout/', views.logout_view, name='logout_view'),
    path('doctor_home_search/', views.doctor_home_search, name='doctor_home_search'),
    path('doctor_search_patient/', views.doctor_search_patient, name='doctor_search_patient'),
    path('pharmacy_home_search/', views.pharmacy_home_search, name='pharmacy_home_search'),
    path('delete_department/<int:department_id>/', views.delete_department, name='delete_department'),
    path('pharmacy_search/', views.pharmacy_search, name='pharmacy_search'),
]
